name: DEVCI
on:
  push:
    branches: [ dev ]  
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment:  
      name: dev
    steps:
    - uses: actions/checkout@v2
    - run:  chmod +x ./.github/actions/laravel-build/dev-entrypoint.sh  
    - run: ./.github/actions/laravel-build/dev-entrypoint.sh      

