name: PRDCI
on:
  # Triggers the workflow on push  events but only for the dev branch
  pull_request:
    branches: [ prd ]
  workflow_dispatch:        
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment:  
      name: prd
    steps:
    - uses: actions/checkout@v2
    - run:  chmod +x ./.github/actions/laravel-build/prd-entrypoint.sh  
    - run: ./.github/actions/laravel-build/prd-entrypoint.sh      
